### ISSUE TITLE
PixelBot for 1.12.1 question

### ISSUE THREAD

**Issue by Darkjamin** [Serenalyw/PixelBot#1]
Hi Sernalyw,

Very nice work on this. I myself play on a SPP with 1.12.1
I wanted to ask if your work could be used in order to get this: https://github.com/Xian55/WowClassicGrindBot working in the 1.12.1?

I made an issue request over there: https://github.com/Xian55/WowClassicGrindBot/issues/450
They also use the idea of an addon to make pixel available for an external program to read, but they seems to have a solid backend already.

I was wondering if you would be interested in looking at it, and how we could get their DataToColor addon work for 1.12.1?

Thank you / Merci.

**Comment by SerenaTetart** [comment]
My guess to make it work on 1.12.1 and other "vanilla" versions is to:
* Modify the lua code *(the addons)* because the API change a lot between season of mastery and old versions of WoW
* Modify the MPQ and DBC paths and maybe some code related to that
After that it should work based on what I've seen of their program.

By the way PixelBot is more of a *toy project*, to really use it you have to code yourself the lua files...

And of course you can use bits of my code for your project, you are free to do whatever you want !

**Comment by bobbe520** [comment]
Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "F:\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "F:\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\Python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-u2a7hsap\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-u2a7hsap\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-u2a7hsap\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-u2a7hsap\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "F:\Python\Lib\inspect.py", line 1285, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "F:\Python\Lib\inspect.py", line 1267, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "F:\Python\Lib\inspect.py", line 1096, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

D:\All Game\PixelBot-master>python src/interface.py
Traceback (most recent call last):
  File "D:\All Game\PixelBot-master\src\interface.py", line 1, in <module>
    from PIL import ImageTk, Image, ImageGrab
ModuleNotFoundError: No module named 'PIL'

**Comment by bobbe520** [comment]
why there is erro ,cant use anymore ?

**Comment by SerenaTetart** [comment]
I no longer maintain this project since I entirely switched to MultiboxBot (https://github.com/SerenaTetart/MultiboxBot) which is 100 times more powerful (though more detectable).

**Comment by bobbe520** [comment]
I see , so therei is none can support TWW the retail verson right ? thx for answering though
